"""The design system. Hardcoded on purpose.

The model picks a palette *name* and nothing else. Every other visual decision —
type scale, easing, spacing, stroke weight — lives here so that a hundred beats
generated by a hundred prompts still look like one film.

Nothing in this module imports manim at module scope, so the whole thing is
importable (and testable) on a machine that has never heard of Cairo.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = [
    "Palette", "PALETTES", "PALETTE_NAMES", "get_palette",
    "FONT_TITLE", "FONT_BODY",
    "EASE_IN", "EASE_OUT",
    "ASPECT_RATIO", "PIXEL_WIDTH", "PIXEL_HEIGHT", "FPS",
    "FRAME_WIDTH", "FRAME_HEIGHT", "MARGIN", "BOTTOM_MARGIN", "CAPTION_ZONE",
    "SAFE_WIDTH", "SAFE_HEIGHT", "SAFE_CENTER_Y",
    "GAP_TIGHT", "GAP", "GAP_WIDE",
    "CORNER_RADIUS", "STROKE_THIN", "STROKE", "STROKE_THICK",
    "CARD_PAD_X", "CARD_PAD_Y", "FILL_OPACITY",
    "MAX_ELEMENTS",
]


# --------------------------------------------------------------------- palette


@dataclass(frozen=True)
class Palette:
    """Four inks and a ground. Never more.

    ``primary`` carries structure, ``secondary`` supports it, ``accent`` is the
    single loudest thing on screen (spend it once per beat), ``muted`` is for
    anything that has said its piece but has not left yet.
    """

    name: str
    bg: str
    primary: str
    secondary: str
    accent: str
    muted: str

    @property
    def colors(self) -> tuple[str, str, str, str]:
        """The four inks, ground excluded."""
        return (self.primary, self.secondary, self.accent, self.muted)

    def cycle(self, index: int) -> str:
        """Deterministic ink for the n-th element of a repeated series."""
        series = (self.primary, self.secondary, self.primary, self.secondary)
        return series[index % len(series)]


PALETTES: dict[str, Palette] = {
    # Deep navy ground. Cyan leads, indigo supports, paper-white is the accent
    # you spend on the one thing that matters, slate retires the rest.
    "cool": Palette(
        name="cool",
        bg="#0A1220",
        primary="#4CC9F0",
        secondary="#4361EE",
        accent="#F5F9FF",
        muted="#5A6B85",
    ),
    # Near-black with a brown bias so amber and coral sit on it without buzzing.
    # Cream is the accent; it reads as lit rather than merely bright.
    "warm": Palette(
        name="warm",
        bg="#14100C",
        primary="#F5A524",
        secondary="#E8654F",
        accent="#FBF1DE",
        muted="#7C6A56",
    ),
    # Charcoal, off-white, grey — and exactly one accent, a low-chroma gold that
    # never competes with the type.
    "neutral": Palette(
        name="neutral",
        bg="#16181C",
        primary="#EDEEF0",
        secondary="#9AA0A6",
        accent="#E0B04A",
        muted="#575C63",
    ),
}

PALETTE_NAMES: tuple[str, ...] = tuple(PALETTES)


def get_palette(name: str) -> Palette:
    """Look up a palette by the name the spec chose.

    Raises ``ValueError`` naming the valid options — an unknown palette is a
    bug in the spec pipeline, never something to paper over with a default.
    """
    try:
        return PALETTES[name]
    except KeyError:
        raise ValueError(
            f"unknown palette {name!r}; valid palettes are: {', '.join(PALETTE_NAMES)}"
        ) from None


# ------------------------------------------------------------------ typography

# Two sizes. That is the entire type scale. A third size is a design smell and
# on a 1080p frame nobody can tell it apart from one of these anyway.
FONT_TITLE = 42
FONT_BODY = 26


# ---------------------------------------------------------------------- easing

_rate_functions = None


def _rf():
    """Manim's rate_functions, resolved on first use.

    Lazy so that importing the theme never drags in manim; falls back to the
    same curves implemented locally when manim is absent, which keeps easing
    values comparable between headless tests and real renders.
    """
    global _rate_functions
    if _rate_functions is None:
        from ._manim import rate_functions

        _rate_functions = rate_functions
    return _rate_functions


def EASE_IN(t: float) -> float:
    """The only entrance easing. Manim's ``smooth`` (quintic, zero-velocity ends)."""
    return _rf().smooth(t)


def EASE_OUT(t: float) -> float:
    """The only exit easing. Cubic ease-out: leaves fast, settles gently."""
    return _rf().ease_out_cubic(t)


# ------------------------------------------------------------------- the frame

ASPECT_RATIO = 16 / 9
PIXEL_WIDTH = 1920
PIXEL_HEIGHT = 1080
FPS = 30

# Manim's scene units for a 16:9 frame of height 8.
FRAME_HEIGHT = 8.0
FRAME_WIDTH = FRAME_HEIGHT * ASPECT_RATIO  # 14.2222…

# Nothing is allowed inside this band. It is where the compositor's framing lives.
MARGIN = 0.6

# The bottom is not symmetric with the rest: Remotion lays word-level captions
# across the bottom 18% of the frame (theme.ts LAYOUT.captionZoneRatio). Anything
# Manim draws down there ends up behind the caption plate, so the safe area stops
# short of it. 0.18 * FRAME_HEIGHT = 1.44 scene units.
CAPTION_ZONE = 0.18 * FRAME_HEIGHT  # 1.44
BOTTOM_MARGIN = CAPTION_ZONE

SAFE_WIDTH = FRAME_WIDTH - 2 * MARGIN
SAFE_HEIGHT = FRAME_HEIGHT - MARGIN - BOTTOM_MARGIN

# Because the top and bottom margins differ, the middle of the safe area is not
# the middle of the frame. Archetypes that centre their content vertically must
# shift it up by this much, or they drift into the caption band.
SAFE_CENTER_Y = (BOTTOM_MARGIN - MARGIN) / 2  # 0.42


# ------------------------------------------------------------------- structure

GAP_TIGHT = 0.30   # label to its own box
GAP = 0.75         # sibling elements
GAP_WIDE = 1.20    # unrelated groups

CORNER_RADIUS = 0.16
STROKE_THIN = 2.0
STROKE = 3.0
STROKE_THICK = 5.0

CARD_PAD_X = 0.45
CARD_PAD_Y = 0.34
FILL_OPACITY = 0.10  # cards are tinted glass, not solid blocks

# The hard ceiling on simultaneous on-screen elements. Mirrors MAX_ELEMENTS in
# packages/spec/src/archetypes.ts — if one moves, both move.
MAX_ELEMENTS = 5
